In [1]:
import numpy as np

# column-based gaussian filter

In [2]:
a = np.array([[1, 2, 1]])/4.0
print a.shape
print a

(1, 3)
[[ 0.25  0.5   0.25]]


# 2D gaussian filter = row-based gaussian * column based gaussian

In [3]:
a2d = np.dot(a.T, a)
print a2d.shape
print a2d

(3, 3)
[[ 0.0625  0.125   0.0625]
 [ 0.125   0.25    0.125 ]
 [ 0.0625  0.125   0.0625]]


# 3D gaussian filter

In [4]:
a3d =  np.dot(a2d[:,:, np.newaxis], a)
print a3d.shape
print a3d

(3, 3, 3)
[[[ 0.015625  0.03125   0.015625]
  [ 0.03125   0.0625    0.03125 ]
  [ 0.015625  0.03125   0.015625]]

 [[ 0.03125   0.0625    0.03125 ]
  [ 0.0625    0.125     0.0625  ]
  [ 0.03125   0.0625    0.03125 ]]

 [[ 0.015625  0.03125   0.015625]
  [ 0.03125   0.0625    0.03125 ]
  [ 0.015625  0.03125   0.015625]]]
