In [1]:
import numpy as np

# column-based gaussian filter

In [13]:
a = np.array([[1, 2, 1]])/4.0
print a.shape
print a

(1, 3)
[[ 0.25  0.5   0.25]]


# 2D gaussian filter = row-based gaussian * column based gaussian

In [14]:
a2d = np.dot(a.T, a)*16
print a2d.shape
print a2d

(3, 3)
[[ 1.  2.  1.]
 [ 2.  4.  2.]
 [ 1.  2.  1.]]


# 3D gaussian filter

In [16]:
 a2d[:,:, np.newaxis].shape

(3, 3, 1)
